# Exploring the Data

url: https://datasets.wri.org/datasets/global-power-plant-database?map=eyJhY3RpdmVMYXllckdyb3VwcyI6W3siZGF0YXNldElkIjoiNTM2MjNkZmQtM2RmNi00ZjE1LWEwOTEtNjc0NTdjZGI1NzFmIiwibGF5ZXJzIjpbIjJhNjk0Mjg5LWZlYzktNGJmZS1hNmQyLTU2YzM4NjRlYzM0OSJdfV0sImJhc2VtYXAiOiJsaWdodCIsImJvdW5kYXJpZXMiOmZhbHNlLCJib3VuZHMiOnsiYmJveCI6bnVsbCwib3B0aW9ucyI6e319LCJsYWJlbHMiOiJkYXJrIiwibGF5ZXJzUGFyc2VkIjpbWyIyYTY5NDI4OS1mZWM5LTRiZmUtYTZkMi01NmMzODY0ZWMzNDkiLHsiYWN0aXZlIjp0cnVlLCJsYXllclNvdXJjZSI6bnVsbCwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZSwiekluZGV4IjoxMX1dXSwidmlld1N0YXRlIjp7ImxhdGl0dWRlIjozOC4xOTg1NzYyODExNDc5OCwibG9uZ2l0dWRlIjo2Ni44NTMzNDY2MzI2NzY2OCwiem9vbSI6MTAuMTAxMTI3NDQwMjIxODE1fX0%3D

In [1]:
# import dataset

import pandas as pd

df_pw = pd.read_csv("global_power_plant_database.csv", low_memory=False)

df_pw

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.3220,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.6700,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.6230,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.5560,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.6410,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,183.79,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34932,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,73.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34933,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,...,575.78,575.78,548.94,579.90,578.32,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,2785.10,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,...,3999.75,3999.75,3745.02,3428.65,3960.24,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

In [5]:
indonesia = df_pw[
    (df_pw["primary_fuel"] == "Coal") & (df_pw["country_long"] == "Indonesia")
]


indonesia

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
15641,IDN,Indonesia,Amamapare Port power station,WRI1075798,195.0,-4.8278,136.8391,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,1061.18,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15643,IDN,Indonesia,Amurang power station,WRI1075799,60.0,1.1825,124.4806,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,326.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15647,IDN,Indonesia,Banten Serang power station,WRI1075800,660.0,-5.8830,106.0459,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,3591.70,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15648,IDN,Indonesia,Batu Hijau power station,WRI1075801,124.0,-8.9012,116.7382,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,674.80,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15653,IDN,Indonesia,Celukan Bawang power station,WRI1075802,381.0,-8.1963,114.8516,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,2073.39,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15786,IDN,Indonesia,Pekanbaru Tenayan power station,WRI1075813,220.0,0.5644,101.5234,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,1197.23,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15788,IDN,Indonesia,Perawang Mill power station,WRI1075814,755.0,0.6893,101.6191,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,4108.69,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15793,IDN,Indonesia,Purwakarta Indorama Power Station,WRI1075815,60.0,-6.5539,107.4137,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,326.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15803,IDN,Indonesia,Sulawesi Mining power station,WRI1075816,280.0,-2.8274,122.1553,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,1523.75,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15808,IDN,Indonesia,Tanjung Awar-Awar power station,WRI1075817,700.0,-6.8105,111.9955,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,3809.38,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1

In [6]:
indonesia_al = df_pw[df_pw["country_long"] == "Indonesia"]


indonesia_al

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
15641,IDN,Indonesia,Amamapare Port power station,WRI1075798,195.000,-4.8278,136.8391,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,1061.18,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15642,IDN,Indonesia,Ampenan,WRI1000736,56.284,-8.5667,116.0667,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,101.59,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15643,IDN,Indonesia,Amurang power station,WRI1075799,60.000,1.1825,124.4806,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,326.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
15644,IDN,Indonesia,Asahan I,WRI1000737,180.000,2.5113,99.2590,Hydro,NaN,NaN,...,614.23,443.82,523.30,555.94,592.43,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
15645,IDN,Indonesia,Bakaru,WRI1000738,126.000,-3.1141,119.6042,Hydro,NaN,NaN,...,423.60,334.58,350.67,415.34,424.69,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15814,IDN,Indonesia,Ubrug/saguling,WRI1001039,18.360,-6.9039,107.6186,Hydro,NaN,NaN,...,67.60,62.66,61.15,72.72,62.42,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
15815,IDN,Indonesia,Ulubelu 1 & 2,WRI1001040,110.000,-5.3096,104.5733,Geothermal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION
15816,IDN,Indonesia,Wayang Windu,WRI1001044,227.000,-7.1966,107.6258,Geothermal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION
15817,IDN,Indonesia,Wlingi - Brantas,WRI1001045,54.000,-8.0776,112.3311,Hydro,NaN,NaN,...,158.18,138.62,149.71,161.31,165.44,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
15818,IDN,Indonesia,Wonorejo - Pamekasan,WRI1001046,6.300,-8.1136,112.2869,Hydro,NaN,NaN,...,24.89,17.37,21.45,26.43,24.77,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

so, we have country names (country_long), longitude and latitude for the power plant, fuel source of the power plant, estimated generation power (in some years) (estimated_generation_gwh_2017)

Importing GeoJSON data

In [3]:
import requests

geo = requests.get(
    "https://r2.datahub.io/clvyjaryy0000la0cxieg4o8o/main/raw/data/countries.geojson"
)
shapes = geo.json()
print("loaded")

loaded

we wll use ISO3166-1-Alpha-3 key to match with the power plant data

In [4]:
def plot_pw(df):
    """This function makes a chloropleth map of NYC, using a DataFrame with a boro_cd and a requests_per_capita column."""

    fig = px.choropleth_map(
        df,
        locations="country",  # column name to match on
        color="capacity_mw",  # column name for values
        geojson=shapes,
        featureidkey="properties.ISO3166-1-Alpha-3",  # GeoJSON property to match on
        center={"lat": 40.71, "lon": -73.98},
        zoom=9,
        height=600,
        title="Requests per capita across Community Districts",
    )

    fig.show()